// FRIENDSHIP
export const RECEIVE_FRIEND_STATUS = "RECEIVE_FRIEND_STATUS";
export const UPDATE_FRIENDSHIP_STATUS = "UPDATE_FRIENDSHIP_STATUS";
export const REQUEST_FRIENDSHIP = "REQUEST_FRIENDSHIP";
export const CANCEL_REQUEST = "CANCEL_REQUEST";
export const ACCEPT_FRIENDSHIP = "ACCEPT_FRIENDSHIP";
export const DELETE_FRIENDSHIP = "DELETE_FRIENDSHIP";

//FRIENDS & PENDING
export const RECEIVE_FRIENDS_PENDING = "RECEIVE_FRIENDS_PENDING";
export const CHANGE_FRIENDPENDING_TOGGLE = "CHANGE_FRIENDPENDING_TOGGLE";

//GALLERY & PHOTOPICKER
export const RECEIVE_PHOTOPICKER_GALLERY = "RECEIVE_PHOTOPICKER_GALLERY";
export const IS_LIGHTBOX_VISIBLE = "IS_LIGHTBOX_VISIBLE";
export const UPDATE_PHOTOPICKER_STARTEND = "UPDATE_PHOTOPICKER_STARTEND";
export const TOGGLE_ISUPLOADERVISIBLE = "TOGGLE_ISUPLOADERVISIBLE";

//LOADING
export const IS_LOADING = "IS_LOADING";

//MESSAGES & CHAT
export const RECEIVE_RECENT_MESSAGES = "RECEIVE_RECENT_MESSAGES";
export const SAVE_NEW_CHATMESSAGE = "SAVE_NEW_CHATMESSAGE";

//OTHER USER
export const RECEIVE_OTHER_USER = "RECEIVE_OTHER_USER";
export const UPDATE_OTHER_USER = "UPDATE_OTHER_USER";
export const RECEIVE_OTHER_USER_FRIENDS = "RECEIVE_OTHER_USER_FRIENDS";
export const FILTER_MUTUAL_FRIENDS = "FILTER_MUTUAL_FRIENDS";

//POTATO BUTTON
export const RECEIVE_POTATOCOUNT = "RECEIVE_POTATOCOUNT";
export const RECEIVE_POTATOBUTTON = "RECEIVE_POTATOBUTTON";
export const CHANGE_POTATOCOUNT = "CHANGE_POTATOCOUNT";

//RESET PASSWORD
export const RESETPW_NEXTSTEP = "RESETPW_NEXTSTEP";

// USER
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_PROFILE_PIC = "UPDATE_PROFILE_PIC";
export const RECEIVE_USER = "RECEIVE_USER";
export const RECEIVE_USERPROFILE = "RECEIVE_USERPROFILE";
export const CHANGE_BIOEDITOR = "CHANGE_BIOEDITOR";

//USER INPUT
export const UPDATE_USERINPUT = "UPDATE_USERINPUT";

//USER SEARCH
export const TOGGLE_ISSEARCHING = "TOGGLE_ISSEARCHING";
export const RECEIVE_MOST_RECENT_USERS = "RECEIVE_MOST_RECENT_USERS";
export const RECEIVE_USER_SEARCH_RESULTS = "RECEIVE_USER_SEARCH_RESULTS";
